version: '3'
services:
  frontend:
    build:
      context: ./src/frontend # Specify the directory where your React frontend code is located
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./src/backend # Specify the directory where your Express.js backend code is located
    ports:
      - "3001:3001"
