version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    command: node src/Api.js
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start