version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - '3000:80'
    volumes:
      - ./Frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - '3001:3001'
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
